=== Zarbotics/diamond_event_be/src/main/resources/fonts/jost/fonts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="fontFamilies">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fontFamily">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="normal" />
							<xs:element name="bold" />
							<xs:element name="italic" />
							<xs:element name="boldItalic" />
							<xs:element name="pdfEncoding" type="xs:string" />
							<xs:element name="pdfEmbedded" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="name" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Zarbotics/diamond_event_be/src/main/resources/fonts/inter/fonts.xml
<?xml version="1.0" encoding="UTF-8"?>
<fontFamilies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="fonts.xsd">
    <fontFamily name="Inter">
        <normal><![CDATA[fonts/inter/Inter-Regular.ttf]]></normal>
        <bold><![CDATA[fonts/inter/Inter-Bold.ttf]]></bold>
        <italic><![CDATA[fonts/inter/Inter-italic.ttf]]></italic>
        <boldItalic><![CDATA[fonts/inter/Inter-BoldItalic.ttf]]></boldItalic>
        <pdfEncoding>Identity-H</pdfEncoding>
        <pdfEmbedded>true</pdfEmbedded>
    </fontFamily>
</fontFamilies>

=== Zarbotics/diamond_event_be/src/main/resources/fonts/playfair/fonts.xml
<?xml version="1.0" encoding="UTF-8"?>
<fontFamilies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="fonts.xsd">

    <fontFamily name="Playfair">

        <!-- Regular -->
        <normal><![CDATA[fonts/playfair/PlayfairDisplay-Regular.ttf]]></normal>

        <!-- Bold -->
        <bold><![CDATA[fonts/playfair/PlayfairDisplay-Bold.ttf]]></bold>

        <!-- Italic -->
        <italic><![CDATA[fonts/playfair/PlayfairDisplay-Italic.ttf]]></italic>

        <!-- Bold Italic -->
        <boldItalic><![CDATA[fonts/playfair/PlayfairDisplay-BoldItalic.ttf]]></boldItalic>

        <!-- Required for PDF rendering -->
        <pdfEncoding>Identity-H</pdfEncoding>

        <!-- IMPORTANT: embed font into PDF -->
        <pdfEmbedded>true</pdfEmbedded>

    </fontFamily>

</fontFamilies>
